# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
swagger: "2.0"
info:
  title: "skserve"
  description: "Get prediction from sklearn model."
  version: "1.0.0"
host: "skserve.endpoints.rising-sea-112358.cloud.goog"
schemes:
  - "https"
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  "/predict":
    post:
      description: "Get prediction given X."
      operationId: "predict"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        -
          name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/X"
      responses:
        200:
          description: "Success."
          schema:
            $ref: "#/definitions/y"
        400:
          description: "Missing X."
definitions:
  X:
    type: "object"
    required:
    - "X"
    properties:
      X:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"
            format: "float"
  y:
    type: "object"
    required:
    - "y"
    properties:
      y:
        type: "array"
        items:
          type: "number"
          format: "float"